# Generated by Django 4.1.5 on 2023-05-02 16:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0014_myuser_age_myuser_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='myuser',
            name='age',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='gender',
        ),
        migrations.RemoveField(
            model_name='myuser',
            name='reivew',
        ),
        migrations.AddField(
            model_name='account',
            name='age',
            field=models.IntegerField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='gender',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='account',
            name='reivew',
            field=models.CharField(max_length=1000, null=True),
        ),
    ]
