# Generated by Django 4.1.5 on 2023-05-16 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0016_account_nickname_account_point_account_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='point',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='profile_img',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='account',
            name='step',
            field=models.IntegerField(null=True),
        ),
    ]
