# Generated by Django 4.1.5 on 2023-05-22 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0017_alter_account_point_alter_account_profile_img_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='account',
            name='age',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
